SPREADSHEET_ID = "161JVy5kmupt8sgERs7n3gx-DBAk1KQnt1712rrLwmac"

[service_account_info]
type = "service_account"
project_id = "team-healthcheck-477016"
private_key_id = "5ff1adae75739977918abfb98a29255a189fdd29"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkk2X1EdM3qlFV
mDV3WFSQnCu0ApezZAtEyjHW/ineVmSvbxUoL4vRtzwhgmks6RdUy+5O3OL9/a6p
IFI22/GpUBIC092vlwMZ1OQ3mTF8ZY0Otn/0LQwRitOx3U+7o608Vt2Jcs6dHxg5
w2poJEVL7u+AGyTz6uzQsv1feSi36vhkAMmOuv6uYBmRV4P9dAuXnkwVYnP7r5fj
X2UW66IuwnUoYERYezryjQGb9Vfg1n91ReS7lP7XN4jptBtD7WkcdMwmUW3lxrTo
lWZeYR3n+uVYDXN2RKD3oNPrQapXt0Qy0CNunx3c+jmhBw10MRrgN1wNgw+CUneG
jbd3nrXZAgMBAAECggEABQfDrN8hG3P3bXbWt4b50BETSDrGDpknEQYJykkALZ1q
vBlYm7RXATopD9slF4F+ZudJfvFDIkFP8TfIMN4TKmTZ+r/QEwRkzLQppPC9RvtG
+aVRZDzA6tkD9Hf6bmv9KQ7R/FgH1wdIHcff0j69kX8ZpKBFG7bZYIhVX0bcRuwj
5D3lqdaz3Ork+km7N/LFL/mtKcTBNPZhJh353PBkEb7iVlwqSHCJd8JJZFDr8CxP
zuSVLYl/I8nQ82x0eZ52/tGS7akPKZ1Ar3/x4Ca1EdDaHJc62+mvex+LCTC5K2FD
Q/eNq3heUMS5nGCq5qrh+s/zEHnmz9yUOGa2BL/ugQKBgQDmT1AxjpqEB77p+agn
eLv6l9rLKmpLLbOZ5ePVTDRenBuxW+yyt+SuhrQlRugz2P9rTZEzJnmJszs3lKWI
4WSBnM3mv68/VbMqZIOW8XY4tDZRg2VjiV3oozhrYMxyeol/TqQ56dE0u47xg9vh
S5E0urxqSyNICSCO61X+RJJcYQKBgQC27v7Ggo++aTChgDUZznA6Dfzo3fHLQBNH
miAVGH2rMwWqUHzF9+Waa36+enS7GL3MacUV2H+LCvFhuT2zEgI2Vbm29YjAYQlM
3SYwSKewKcnTkQIEUfZTLlelg1pw9H09nAKjKcPSHAZsE2uh0Uf/fUPWNQNSyCUu
qcud62yMeQKBgAzkwdOUbTgZCuokbPKQws1btQcMv9innVdvVFr7oi7txGsgf1be
DrJqnik8GAHXEy2ZsRhQ/hrkattIuh+4ppzO/4P8lT4ReS9VYzyPFhREmonjtkhl
R1mf0afJSojaLVpwN6d6XJj8KxuAS04Iof92uNemjzoYMLdvm2fZxOvhAoGAJGMt
snbN+OYbkkRaS6PQlvupTvi22+MG8rspnoiclq0zd0lDSG2i8jBnqaPaDE1Dk6GG
Xm4OEK5AjVu3diMi5YPvyQDWDs4+d1eV/Qy2rkfhqX+ykwFqqekR7g5OsyEuuE6M
B8CK/wQsEttaEXn7hEp6b+Vjn9fH7ZxAsEzf7qECgYApQg8hC3gd7a2AwqBtVmUM
wKeu76uRqBiVoZ4rAIqHphlf/9LYNf5FaQsBK71b6G9KeQq0wI0/qKk1VyCTxgY8
VEluUOT2ffjTe7ZU2yVUETXDdrPZ5VZkH17yC4ZZfpmsKlJKWnORBjIq8J6VR3px
c+E0/xZjNLWX/Hjrq+W/NA==
-----END PRIVATE KEY-----
"""
client_email = "healthcheck-bot@team-healthcheck-477016.iam.gserviceaccount.com"
client_id = "109652671327143950044"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/healthcheck-bot%40team-healthcheck-477016.iam.gserviceaccount.com"
universe_domain = "googleapis.com"